server:
  port: 8761

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-registry

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

    serviceUrl:
       defaultZone: http://localhost:8761/eureka/


  instance:
    hostname: localhost








