server:
  port: 8088

#by default profile is Git because our config server should fetch configuration from git
  #But we can change it to local configuration by using profiles native
spring:
  profiles:
    active: native

  application:
    name: config-server

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411